[package]
name = "codeadvent24"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"

[profile.release]
lto = "thin"
debug = false
codegen-units = 1
overflow-checks = false
panic = "abort"
